### ISSUE TITLE
Uncrouching midair lets you get stuck in blocks

### ISSUE THREAD

**Issue by Disttraction** [QuantumV2/super-mario-bros-gml#4]
https://github.com/QuantumV2/super-mario-bros-gml/assets/119495916/387e565b-89ce-4bd2-ba28-ad93c180c864

**Comment by QuantumV2** [comment]
i dont think its supposed to be possible to uncrouch in mid air. ill fix that soon

**Comment by QuantumV2** [comment]
fixed in commit 1e8d868
