### ISSUE TITLE
Crouching behaves extremely weirdly

### ISSUE THREAD

**Issue by Disttraction** [QuantumV2/super-mario-bros-gml#6]
https://github.com/QuantumV2/super-mario-bros-gml/assets/119495916/590b3bbb-b671-419d-b54c-0ed3d86bdfca

**Comment by Disttraction** [comment]
To go into more detail, it stops momentum midair and slows you to a halt way too early on the ground.

**Comment by QuantumV2** [comment]
fixed in commit 1e8d868
